app/__init__.py
from os import path
from os import mkdir
from os import environ
from secrets import token_bytes

from flask import g
from flask import Flask
from flask import Response
from flask_redis import FlaskRedis
from dotenv import load_dotenv

redis = FlaskRedis()
BASE_DIR = path.dirname(path.abspath(__file__))
UPLOAD_DIR = path.join(BASE_DIR, "upload")


def upload_path_test():
    if not path.isdir(UPLOAD_DIR):
        mkdir(UPLOAD_DIR)


def get_secret_key() -> bytes:
    try:
        with open(".SECRET_KEY", mode="rb") as key_reader:
            key = key_reader.read()
    except FileNotFoundError:
        with open(".SECRET_KEY", mode="wb") as key_writer:
            key = token_bytes(32)
            key_writer.write(key)

    return key


def create_app():
    load_dotenv()
    upload_path_test()

    app = Flask(__name__)
    app.config['MAX_CONTENT_LENGTH'] = int(environ['MAX_SIZE']) * 1000 * 1000
    app.config['REDIS_URL'] = environ['REDIS_URL']
    app.config['SECRET_KEY'] = get_secret_key()

    # redis init
    redis.init_app(app=app)

    # blueprint init
    from app import views
    for view in views.__all__:
        app.register_blueprint(getattr(getattr(views, view), "bp"))

    # filter init
    from app import template_filter
    for x in [x for x in [getattr(template_filter, x) for x in dir(template_filter) if not x.startswith("_")] if x.__class__.__name__ == "function"]:
        app.add_template_filter(x)

    # register error handler
    from .error import error_map
    for code in error_map:
        app.register_error_handler(code, error_map[code])

    @app.before_request
    def set_title():
        g.title = "업로드"

    @app.get("/robots.txt")
    def txt():
        return Response(
            response="\n".join([
                "User-agent: *",
                "Allow: /$",
                "Allow: /static",
                "Disallow: /",
            ]),
            mimetype="text/plain"
        )

    return app

app/views/__init__.py
__all__ = [
    "download",
    "file",
    "files",
    "upload",
]

from . import *

app/views/download.py
from io import BytesIO
from json import loads
from os.path import join

from flask import Blueprint
from flask import abort
from flask import send_file

from app import redis
from app import UPLOAD_DIR
from app.tuples import File

bp = Blueprint("download", __name__, url_prefix="/download")


@bp.get("/<string:file_id>")
@bp.get("/<string:file_id>/<string:fake>")
def file(file_id: str, fake=None):
    from_redis = redis.get(f"chick0/upload:{file_id}")
    if from_redis is None:
        return abort(404)

    from_redis = loads(from_redis)
    file_ = File(*from_redis)

    try:
        with open(join(UPLOAD_DIR, file_id), mode="rb") as tmp_reader:
            blob = tmp_reader.read()
    except FileNotFoundError:
        return abort(404)

    return send_file(
        BytesIO(blob),
        mimetype="application/octet-stream",
        as_attachment=True,
        attachment_filename=file_.name
    )

app/views/file.py
from json import loads

from flask import Blueprint
from flask import g
from flask import abort
from flask import request
from flask import session
from flask import url_for
from flask import render_template

from app import redis
from app.tuples import File
from app.tuples import Error

bp = Blueprint("file", __name__, url_prefix="/file")


@bp.get("/<string:file_id>")
def show(file_id: str):
    from_redis = redis.get(f"chick0/upload:{file_id}")
    if from_redis is None:
        return abort(404)

    from_redis = loads(from_redis)
    file = File(*from_redis)

    g.title = file.name
    return render_template(
        "file/show.html",
        file_id=file_id,
        file=file,
        download_url="{host}{path}".format(
            host="{scheme}://{host}".format(scheme=request.scheme, host=request.host),
            path=url_for("download.file", file_id=file_id, fake=file.name),
        )
    )


@bp.get("/<string:file_id>/delete")
def delete(file_id: str):
    from_redis = redis.get(f"chick0/upload:{file_id}")
    if from_redis is None:
        return abort(404)

    file = File(*loads(from_redis))

    if session.get(file_id, "undefined") != file.code:
        return abort(403)

    redis.delete(f"chick0/upload:{file_id}")
    del session[file_id]

    return render_template(
        "file/deleted.html"
    )

app/views/files.py
from json import loads

from flask import Blueprint
from flask import session
from flask import render_template

from app import redis
from app.tuples import File

bp = Blueprint("files", __name__, url_prefix="/files")


@bp.get("")
def show_all():
    files = []
    file_id_storage = {}
    for file_id in session.keys():
        t = redis.get(f"chick0/upload:{file_id}")
        if t is not None:
            file = File(*loads(t))
            if file.code == session[file_id]:
                files.append(file)
                file_id_storage[file.code] = file_id

    return render_template(
        "files/show_all.html",
        files=files,
        file_id_storage=file_id_storage
    )

app/views/upload.py
from json import dumps
from os.path import join
from hashlib import sha256
from secrets import token_bytes
from datetime import datetime

from flask import Blueprint
from flask import current_app
from flask import session
from flask import request
from flask import redirect
from flask import url_for
from flask import render_template
from flask import Response
from werkzeug.utils import secure_filename

from app import redis
from app import UPLOAD_DIR
from app.custom_error import *
from app.tuples import File

bp = Blueprint("upload", __name__, url_prefix="/")


def set_filename(file_id: str, filename: str) -> str:
    try:
        filename, ext = filename.rsplit(".", 1)
    except ValueError:
        filename = secure_filename(filename)
        return filename if len(filename) != 0 else file_id

    filename = secure_filename(filename)

    if len(filename) == 0:
        filename = f"{file_id}.{ext}"
    else:
        filename += f".{ext}"

    return filename


@bp.get("")
def form():
    return render_template(
        "upload/form.html",
        max_size=current_app.config['MAX_CONTENT_LENGTH']
    )


@bp.post("")
def upload():
    def check_file_id(length: int = 2) -> str:
        new_id = token_bytes(length).hex()
        if redis.exists(f"chick0/upload:{new_id}"):
            return check_file_id(length=length + 1)

        return new_id

    target = request.files.get("file", None)
    if target is None:
        raise FileIsEmpty

    file_id = check_file_id()
    blob = target.stream.read()
    size = len(blob)

    if size == 0:
        raise FileIsEmpty

    if size >= current_app.config['MAX_CONTENT_LENGTH']:
        raise FileIsTooBig

    with open(join(UPLOAD_DIR, file_id), mode="wb") as tmp_writer:
        tmp_writer.write(blob)

    file = File(
        name=set_filename(
            file_id=file_id,
            filename=target.filename
        ),
        size=size,
        sha256=sha256(blob).hexdigest(),
        code=token_bytes(3).hex(),
        creation_date=datetime.now().timestamp()
    )

    redis.set(
        name=f"chick0/upload:{file_id}",
        value=dumps(file),
        ex=2700
    )

    if "curl" in request.user_agent.string:
        return Response(
            response=f"{request.scheme}://{request.host}" + url_for("download.file", file_id=file_id),
            mimetype="text/plain"
        )

    session[file_id] = file.code

    return redirect(url_for("file.show", file_id=file_id))

app/templates/error.html
{% extends 'layout.html' %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">{{ error.title }}</h1>
        <h2 class="subtitle">{{ error.subtitle|safe }}</h2>
    </div>
</section>
{% endblock %}

app/templates/file/deleted.html
{% extends 'layout.html' %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">파일 삭제</h1>
        <h2 class="subtitle">해당 파일이 서버에서 삭제되었습니다.</h2>
    </div>
</section>
{% endblock %}

{%block script %}
<script>
    setTimeout(() => { location.href = '/' }, 1500);
</script>
{% endblock %}

app/templates/file/show.html
{% extends 'layout.html' %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">{{ file.name }}</h1>

        <div class="block buttons">
            <a class="button is-info is-light is-medium" href="{{ url_for('download.file', file_id=file_id, fake=file.name) }}">파일 다운로드</a>
            <button class="button is-link is-light is-medium copy" data-clipboard-text="{{ download_url }}">링크 복사</button>
        {% if session[file_id] %}
            <a class="button is-danger is-light is-medium" href="{{ url_for('file.delete', file_id=file_id) }}">파일 삭제</a>
        {% endif %}
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-2"><b>SHA256</b></div>
            <div class="column">{{ file.sha256 }}</div>
        </div>
        <div class="columns">
            <div class="column is-2"><b>FILE SIZE</b></div>
            <div class="column">{{ file.size|display_size }} ({{ file.size }})</div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script src="{{ url_for('static', filename='js/clipboard.min.js') }}"></script>
<script>
    const clipboard = new ClipboardJS(".copy");
    clipboard.on("success",function(e){e.clearSelection(),window.alert("복사되었습니다.");});
</script>
{% endblock %}

app/templates/files/show_all.html
{% extends 'layout.html' %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">내 파일</h1>
    {% if files|length == 0 %}
        <div class="notification is-danger">
            업로드한 파일이 없습니다!
        </div>
    {% endif %}
    </div>
</section>

<section class="section">
    <div class="container">
    {% for file in files %}
        <div class="box" data-url="/file/{{ file_id_storage[file.code] }}">
            <h4 class="title is-4">{{ file.name }}</h4>
            <p class="subtitle">{{ file.creation_date|parse_timestamp|safe }}</p>
        </div>
    {% endfor %}
    </div>
</section>
{% endblock %}

{% block script %}
<script>
    document.querySelectorAll("div.box").forEach((element) => {
	    element.addEventListener('click', () => {
            location.href = element.dataset.url;
	    });
    });
</script>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>{{ g.title }}</title>

        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, shrink-to-fit=no">
        <meta name="keywords" content="파일 공유, 파일, 업로드, 웹 사이트">
        <meta name="description" content="업로드한 파일은 45분뒤에 삭제됩니다.">

        <meta property="og:type" content="website">
        <meta property="og:locale" content="ko_KR">
        <meta property="og:title" content="{{ g.title }}">
        <meta property="og:description" content="업로드한 파일은 45분뒤에 삭제됩니다.">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.min.css') }}">
    </head>
    <body>
        <nav class="navbar container">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">업로드</a>
                <a role="button" class="navbar-burger" data-target="navbar">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
            </div>
            <div id="navbar" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="/files">
                        내 파일
                    </a>
                </div>
            </div>
        </nav>

        {% block content %}{% endblock %}

        <script src="/static/js/burger.js"></script>
        {% block script %}{% endblock %}
    </body>
</html>

app/templates/upload/form.html
{% extends 'layout.html' %}
{% block content %}
<section class="section">
    <div class="container">
        <h1 class="title is-1">파일 업로드</h1>
        <h2 class="subtitle">업로드한 파일은 <b>45분</b>뒤에 삭제됩니다.</h2>
    </div>
</section>

<section class="section">
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class="field is-grouped">
                <div class="control">
                    <div class="file is-medium">
                        <label class="file-label">
                            <input class="file-input" type="file" name="file" id="fileInput" required="required">
                            <span class="file-cta" id="fileLabel">선택된 파일 없음</span>
                        </label>
                    </div>
                </div>
                <div class="control">
                    <button type="submit" class="button is-info is-light is-medium">업로드</button>
                </div>
            </div>
        </form>

        <p class="block">최대 <b>{{ max_size|display_size }}</b>까지 업로드 할 수 있습니다.</p>
    </div>
</section>
{% endblock %}
{% block script %}
<script>
    const fileInput = document.getElementById("fileInput");
    fileInput.onchange = function(){
        if (fileInput.files.length == 1) {
            if(fileInput.files[0].size >= {{ max_size }}) {
                window.alert("업로드 하려는 파일의 크기가 너무 큽니다."); fileInput.value="";
            } else {
                document.getElementById("fileLabel").innerText = "파일 선택 완료!";
            }
        } else {
            document.getElementById("fileLabel").innerText = "선택된 파일 없음";
        }
    }
</script>
{% endblock %}